### PR TITLE
Submit new button, tab and overflow issue

### PR DESCRIPTION
**Pull request by taylorziegler**
- Added the submit new button
- Fixed the tab issue that Alex mentioned
- Split the job information output into two columns in the previous jobs page so it can be read

### CODE REVIEW

**Comment by mitkotak** [comment]
@taylorziegler Can you fix this typo and add it to your PR ? (https://github.com/cybergis/cybergis-compute-python-sdk/blob/11c5c6fd2a00e75e274bc1d6f965c9252e736dd9/cybergis_compute_client/UI.py#L198)

**Comment by taylorziegler** [comment]
@mitkotak Yes, thanks for pointing that out

**Comment by alexandermichels** [comment]
When using this code, I get the following error:

Screenshot from 2022-06-29 10-21-42

It seems to be that this line is under indented: https://github.com/taylorziegler/cybergis-compute-python-sdk/blob/new-job/cybergis_compute_client/Job.py#L447 We may also want to apply your new job formatting to the job printed out on the "Your Job Status" tab

**Comment by alexandermichels** [comment]
Everything seems to be working for me and code looks good. Great work @taylorziegler

**Pull request merged**
