### PR TITLE
fixed issue with dropdowns

### PR DESCRIPTION
**Pull request by taylorziegler**

### CODE REVIEW

**Comment by alexandermichels** [comment]
@taylorziegler this failed the flake8 test

**Comment by mitkotak** [comment]
@taylorziegler Does this help resolve the import issue ? https://github.com/cybergis/cybergis-compute-python-sdk/blob/bd1506520386be0598c8540095acf62a97cad604/cybergis_compute_client/__init__.py

**Comment by alexandermichels** [comment]
> @taylorziegler Does this help resolve the import issue ? https://github.com/cybergis/cybergis-compute-python-sdk/blob/bd1506520386be0598c8540095acf62a97cad604/cybergis_compute_client/__init__.py

Yeah that should tell flake8 to ignore it: https://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html#in-line-ignoring-errors

**Comment by alexandermichels** [comment]
When I tested this against cgjobsup-dev.cigi.illinois.edu, I got the following error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/.local/python3-0.9.0/lib/python3.8/site-packages/cybergis_compute_client/UI.py:516, in UI.renderRecentlySubmittedJobs(self)
    514 job = self.compute.get_job_by_id(jobs['job'][i]['id'], verbose=False)
    515 jobDetails = jobs['job'][i]
--> 516 job._print_job_formatted(jobDetails)
    517 if self.refreshing:
    518     self.recently_submitted['submit'][jobs['job'][i]['id']] = widgets.Button(description="🔁 Loading", disabled=True)

File ~/.local/python3-0.9.0/lib/python3.8/site-packages/cybergis_compute_client/Job.py:378, in Job._print_job_formatted(self, job)
    366 """
    367 Displays information about the job formatted in a way that can be read with no horizonal scroll bar
    368 """
    370 headers = [
    371     'id', 'slurmId', 'hpc', 'executableFolder', 'dataFolder',
    372     'resultFolder', 'param', 'slurm', 'userId', 'maintainer',
    373     'createdAt']
    374 data = [[
    375     job['id'],
    376     job['slurmId'],
    377     job['hpc'],
--> 378     job['executableFolder'],
    379     job['dataFolder'],
    380     job['resultFolder'],
    381     json.dumps(job['param']),
    382     json.dumps(job['slurm']),
    383     job['userId'],
    384     job['maintainer'],
    385     job['createdAt'],
    386 ]]
    388 dataCol1 = [[]]
    389 dataCol1[0] = data[0][0:5]

KeyError: 'executableFolder'
```

Screenshot from 2022-07-11 17-31-16

Do you have the same error when you test it against dev? The cells I'm using are:

Install this PR from the latest commit: https://github.com/cybergis/cybergis-compute-python-sdk/pull/33/commits/b4392e3759a0622d46c858fe05246f33511ea988

```
!pip install git+https://github.com/cybergis/cybergis-compute-python-sdk.git@b4392e3759a0622d46c858fe05246f33511ea988
```

Instantiate cybergis object connecting to dev

```
from cybergis_compute_client import CyberGISCompute

cybergis = CyberGISCompute(url="cgjobsup-dev.cigi.illinois.edu", isJupyter=True, protocol="HTTPS", port=443, suffix="v2")
```

Show the UI:

```
cybergis.show_ui()
```

Then switch to the Jobs tab.


It seems that with the refactor many of the Job dictionary keys changed names: https://github.com/cybergis/cybergis-compute-python-sdk/blob/d046a2aea584942b9f2ec59970dd10e72e5b770a/cybergis_compute_client/Job.py#L335

**Comment by alexandermichels** [comment]
The code all seems to work. Great work @taylorziegler!

**Pull request merged**
